### ISSUE TITLE
Issue about two features (LinesCovAcc & LinesCovNew)

### ISSUE THREAD

**Issue by vineashovo** [eth-sri/learch#2]
Hi:

When I'm running LEARCH, I find that the two features below are always zero in every piece of data:

* Number of new source lines covered along state’s path (LinesCovAcc)
* Number of new source lines covered by state’s branch (LinesCovNew)

I tried to figure out the reason. And it seems that LEARCH fails to enter the if statement in line 351 of `klee/lib/Core/StatsTracker.cpp`. The "environment" never appears in any of the `cov`.

```cpp
if (cov.find("environment") != std::string::npos) {
  if (ExecutionState::allCoveredSource.find(cov) == ExecutionState::allCoveredSource.end()) {
    es.coveredSource.insert(cov);
    ExecutionState::allCoveredSource.insert(cov);
  }
}
```

My questions are as follows:

* Under what circumstances can we find the "environment" in `cov`?
* Should I change the `!=` into `==` ?

Thank you ;-)!

**Comment by LostBenjamin** [comment]
Hi,

Thanks for your interest in LEARCH!

The benchamrks used in our experiments are placed under a directory named `environment`. Therefore, the condition `if (cov.find("environment") != std::string::npos)` is used as a trick to ensure that only coverage from the benchmarks is counted and coverage from library code is excluded.

Since the condition does make sense in general, I have removed it in [this commit](https://github.com/eth-sri/learch/commit/123b9865282251c00a595c136afe1c6d55ea96ee) for simplicity. Or you can change it yourself to suit your needs.

Best,
Jingxuan

**Comment by vineashovo** [comment]
Thanks! That sovled my doubt.
